services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=petpal_db
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes # เปลี่ยนเป็นรูปแบบ List เพื่อความชัวร์
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    container_name: petpal_backend
    ports:
      - "5000:5000"
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:@db/petpal_db
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: petpal_frontend
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    depends_on:
      - backend